---
- hosts: all
  tasks:
    - debug:
        msg: >- 
            {% if ansible_user=="root" %}
            To jest centos1
            {% elif ansible_user=="vagrant" %}
            To jest ubuntu lub centos2
            {% else %}
            Nie wiem co to jest
            {% endif %}
...
