---
- name: Database Setup Playbook
  hosts: ubuntu2
  become: true
  vars:
    db_user: admin
    db_password: Passw0rd
    db_name: testdb

  tasks:
    - name: Ensure PostgreSQL is installed
      apt:
        name: postgresql
        state: latest
        update_cache: yes

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
...
