---
- hosts: centos1
  vars:
    server_ip: 192.168.24.142
  tasks:
    - lineinfile:
        path: /home/vagrant/test_directory/test_file.txt
        line: 'nameserver {{ server_ip }}'
        create: yes
