# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansible-controller" do |ansible_controller|
    ansible_controller.vm.box = "generic/ubuntu2204"
    ansible_controller.vm.hostname = 'ansible-controller'

    # by default ip "127.0.0.1" port: 2222
    # ansible_controller.vm.network "private_network", ip: "34.116.143.190"

    ansible_controller.vm.network "public_network"

    # set name of the virtualbox and change the default graphic's controller
    ansible_controller.vm.provider :virtualbox do |vb|
      vb.name = 'ansible-controller2'
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end

    # sshpass is needed in order to connect via ssh using password (instead of host key)
    ansible_controller.vm.provision "shell", inline: <<-SHELL
      apt-get update && sudo apt-get upgrade -y
      apt-get install -y sshpass
    SHELL
  end

end
